# MODEL HYPERPARAMETERS
prpdim: 64
prpdepth: 3
popdim: 64
popdepth: 3
zdim: 64
decdim: 64
decdepth: 3
n_embed: 10
poolf: "mean-max"
gen_sigma: "diag"
ema: false
activation: "swish"

# LOSS FUNCTION
beta: 0.25

# OPTIMIZATOIN PARAMETERS
batchsize: 64
epochs: 10000
lr: 0.0005


# EARLY STOPPING PARAMETERS
check_every: 20
patience: 1000

# IDENTIFIER
# uuid ??
init_seed: 5