# MODEL HYPERPARAMETERS
hdim: 64
depth: 3
zdim: 32
n_embed: 10
ema: false
activation: "swish"

# LOSS FUNCTION
beta: 0.25

# OPTIMIZATOIN PARAMETERS
batchsize: 64
epochs: 10000
lr: 0.0005


# EARLY STOPPING PARAMETERS
check_every: 20
patience: 1000

# IDENTIFIER
# uuid ??
init_seed: 3